### ISSUE TITLE
Update site not found..

### ISSUE THREAD

**Issue by JohnVesey** [marcorensch/Joomla-NXD-E-Mail-Authentication-Plugin#1]
Hi,
Thank you for the extension - very helpful :-)

Just to let you know that the Joomla backend (J5.0.0) cannot access the extension's update URL, so a warning is shown every time I go to update another extension. Means I need to manually check for updates.

Many thanks

John V

**Comment by marcorensch** [comment]
@JohnVesey Sorry for the late response. The XML was invalid - solved now. Sorry about that.

**Comment by JohnVesey** [comment]
Thank you so much for this - such a useful extension. Downloaded the update and will install shortly.

Hope my report helped.

John V
